# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - CycleSense

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'      

      - name: Install npm packages - server
        run: |
          cd mern/server
          npm install       
      
      - name: Install npm packages, build then copy files - client
        run: |
          cd mern/client
          npm install
          npm run build
          cp -r ./build ../server/public
            
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: cyclesense
          path: mern/server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: cyclesense

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CycleSense'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F94C2A6622F04195803068B6D181DD9D }}
          package: .
